### ISSUE TITLE
No cut-off for 9VAC power line

### ISSUE THREAD

**Issue by juntek** [bwack/C64-Saver-bwack#19]
Since C64 uses 9VAC to power the SID chip, it is advisable for the 9V AC power line to be cut-off in case of 5V overvoltage as well. Otherwise the SID chip remains powered, while the rest of the computer is not.

**Comment by bwack** [comment]
This will require a lot more components to fix something that will only happen in a 5V rail overvoltage condition. The sid will survive having only 9VAC supply running.
