### ISSUE TITLE
Gerber for addon board not latest version

### ISSUE THREAD

**Issue by wishus3** [bwack/C64-Saver-bwack#23]
"If you are looking for Gerbers, click the releases tab. There you will find a zip file of Gerber for each release."
Clicking on Releases only nets AddonBoard1_2_gerber.zip.
Has v1.3 not been released as Gerber yet?

**Comment by bwack** [comment]
Thanks for feedback. V1.3 where only locally here on my file and never sent to github. Here they are now:
https://github.com/bwack/C64-Saver-bwack/releases/tag/addon1.3

**Comment by bwack** [comment]
Hi wishus3. Did you try building this ?
