### ISSUE TITLE
C64 Saver parts

### ISSUE THREAD

**Issue by juntek** [bwack/C64-Saver-bwack#3]
Since the IRF9332PBF transistor seems not to be manufactured anymore and is difficult to buy, which transistor would you recommend as a replacement for the IRF9332PBF?

**Comment by bwack** [comment]
PMOS SOIC8
VGS max 20V or more
Vds max -30V less is also ok. Hsa to withstand -12V, but also spikes. so -30V is good.
Rds(on)@10V <50mOhm. Could be higher but then more voltage drop.

There is a lot of pincompatible ones.

**Comment by bwack** [comment]
Try SI4497DY-T1-GE3. Seems awesome. 4mOhm Rds(on) @ 4.5V Vgs. The other specs are similar to the IRF9332.

**Comment by VintageProject** [comment]
I wanted to add to the parts discussion.
I found that the original parts aren't easily to be found in Germany, or not at all.

So I tried to find suitable replacements.

**TL431:**
Not too critical.
Available replacement in the same case: TI TL431AILP

Mouser: https://www.mouser.de/ProductDetail/Texas-Instruments/TL431AILP?qs=sGAEpiMZZMtYFXwiBRPs0%2f7Wjg7mAO1C

**2N7002:**
Part number not found.
Available alternative: ON 2N7000

Mouser: https://www.mouser.de/ProductDetail/ON-Semiconductor/2N7000?qs=sGAEpiMZZMvAvBNgSS9LqnnYLgu9ZZAG

**IRF9332PBF:**
Phased out.
As bwack already stated, the alternative is the Vishay SI4497DY-T1-GE3.
Potential issue: The case is SO8, and only one of three source pins will be connected. Given that the original part only had one source pin, I don't expect an issue on this side.

Mouser: https://www.mouser.de/ProductDetail/Vishay-Siliconix/SI4497DY-T1-GE3?qs=%2fha2pyFadugwXmg2weQRtlSGZl1T2oKeZ8ZLxM035MAb87%252bcsFsOkQ%3d%3d

Those are the parts that I found.

FYI: I think Mouser, despite having a German branch, always ships from the US. Expect lead times around a week if you cough up the FedEx delivery fees. Not too bad, but something to consider.

Reichelt.de was a nope, as I did only find the TL431 in an SMT package.

Cheers,
Thilo

**Comment by discoHR** [comment]
Mouser has free FedEx shipping for orders over €50 (at least for Croatia). I buy all my stuff there and always spend €50+ per order. FedEx is super fast too, once Mouser sends the package it's on my door within the next 24 hours. It's 3 days waiting time on average. They're using "USA -> France (customs) -> EU country" route. Just pick the option for Mouser to pay the VAT at checkout, they'll automatically bill you the French VAT rate (20%) and that's all, no more hidden costs.

**Comment by bwack** [comment]
Note that juntek asked for a part used in saver 1.x.

**Comment by bwack** [comment]
I'll have a go at the saver 2.0 tonight to find the resistor values. R1, R2 and R4 are the ones that sets the threshold and hysteresis. I'll use the same values from C64 Saver 1.3. The circuits are very similar, Allthough R6 might have an effect on the hysteresis too. v1.x did not have this resistor. It's there for protection.

PDF: https://github.com/bwack/C64-Saver-bwack/blob/master/C64%20Saver%202.1/C64Saver2.pdf

**Comment by bwack** [comment]
Mosfet C64 Saver 2: IRFR5305PBF
